name: Picodrive CI
on: [push, pull_request]
jobs:

  build-ps2:
    runs-on: ubuntu-latest
    container: ps2dev/ps2dev
    steps:
    - name: build environment
      run: |
        apk add build-base cmake git zip make
    - uses: actions/checkout@v4
      with:
        submodules: true
    - name: build
      run: |
        export CROSS_COMPILE=mips64r5900el-ps2-elf-
        git config --global --add safe.directory $PWD
        ver=$(cut -d'"' -f2 platform/common/version.h)-$(git rev-parse --short HEAD)
        ./configure --platform=ps2
        make -j$(getconf _NPROCESSORS_ONLN)
        make -C platform/ps2 rel VER=$ver
    - name: artifacts
      uses: actions/upload-artifact@v4
      with:
        name: PS2
        path: PicoDrive_ps2_*.zip
        
