name: Picodrive CI
on: [push, pull_request]
jobs:

  build-libretro:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: true
    - name: make
      run: LDFLAGS=-Wl,--no-undefined make -j$(getconf _NPROCESSORS_ONLN) -f Makefile.libretro
    - name: artifacts
      uses: actions/upload-artifact@v4
      with:
        name: Libretro-linux
        path: picodrive_libretro.so

  build-win32:
    runs-on: ubuntu-latest
    container: ghcr.io/irixxxx/toolchain-win32
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: true
    - name: build
      run: |
        git config --global --add safe.directory $PWD
        ver=$(cut -d'"' -f2 platform/common/version.h)-$(git rev-parse --short HEAD)
        ./configure --platform=win32
        make -j$(getconf _NPROCESSORS_ONLN)
        mv PicoDrive.zip PicoDrive-win32-$ver.zip
    - name: artifacts
      uses: actions/upload-artifact@v4
      with:
        name: Win32
        path: PicoDrive-win32*.zip

  build-psp:
    runs-on: ubuntu-latest
    container: pspdev/pspdev
    steps:
    - name: build environment
      run: |
        apk add git gcc g++ zip
    - uses: actions/checkout@v4
      with:
        submodules: true
    - name: build
      run: |
        export CROSS_COMPILE=psp-
        git config --global --add safe.directory $PWD
        ver=$(cut -d'"' -f2 platform/common/version.h)-$(git rev-parse --short HEAD)
        ./configure --platform=psp
        make -j$(getconf _NPROCESSORS_ONLN)
        make -C platform/psp rel VER=$ver
    - name: artifacts
      uses: actions/upload-artifact@v4
      with:
        name: PSP
        path: PicoDrive_psp_*.zip

  build-ps2:
    runs-on: ubuntu-latest
    container: ps2dev/ps2dev
    steps:
    - name: build environment
      run: |
        apk add build-base cmake git zip make
    - uses: actions/checkout@v4
      with:
        submodules: true
    - name: build
      run: |
        export CROSS_COMPILE=mips64r5900el-ps2-elf-
        git config --global --add safe.directory $PWD
        ver=$(cut -d'"' -f2 platform/common/version.h)-$(git rev-parse --short HEAD)
        ./configure --platform=ps2
        make -j$(getconf _NPROCESSORS_ONLN)
        make -C platform/ps2 rel VER=$ver
    - name: artifacts
      uses: actions/upload-artifact@v4
      with:
        name: PS2
        path: PicoDrive_ps2_*.zip
        
